export const CREATE_EVENT = 'CREATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const FETCH_ATTEMPT = 'FETCH_ATTEMPT';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_ALL_EVENTS = 'FETCH_ALL_EVENTS';